# dashboard_gen.py
import pandas as pd
from pathlib import Path
from jinja2 import Template

HTML = """
<!doctype html>
<html>
<head><meta charset="utf-8"><title>Top-10k Preview</title></head>
<body>
<h1>Top-10k Preview</h1>
<h2>Dataset Preview</h2>
<p>Total rows<br/><strong>{{n}}</strong></p>
<p>Sum USD<br/><strong>${{sum_usd}}</strong></p>
<p>Median USD<br/><strong>${{med_usd}}</strong></p>
<p>Mean lead score<br/><strong>{{mean_ls}}</strong></p>
<h3>Top 50 by USD</h3>
<table border="1" cellpadding="6" cellspacing="0">
<tr><th>Address</th><th>USD</th><th>Lead</th><th>Exchange?</th></tr>
{% for r in top %}
<tr>
  <td>{{r.address}}</td>
  <td>${{ '%.2f'|format(r.usd_value) }}</td>
  <td>{{r.lead_score}}</td>
  <td>{{'Y' if r.exchange_deposit_flag else 'N'}}</td>
</tr>
{% endfor %}
</table>
<p>Autogenerated preview</p>
</body>
</html>
"""

def main(csv_path, out_dir):
    out = Path(out_dir); out.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(csv_path)
    top = df.sort_values("usd_value", ascending=False).head(50)
    html = Template(HTML).render(
        n=len(df),
        sum_usd=int(df["usd_value"].fillna(0).sum()),
        med_usd=int(df["usd_value"].fillna(0).median()),
        mean_ls=round(df["lead_score"].fillna(0).mean(), 1),
        top=top.to_dict(orient="records")
    )
    (out / "index.html").write_text(html)
    print("Wrote dashboard", out / "index.html")

if __name__ == "__main__":
    import sys
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "data/run_final/delivery/dashboard")
