import pandas as pd
from pathlib import Path
from jinja2 import Template

HTML = """
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Top-10k Preview</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
<style>
  body{max-width:1200px;margin:20px auto}
  table{width:100%;border-collapse:collapse}
  th,td{padding:8px 10px;text-align:left}
  .metric{display:inline-block;margin-right:20px}
</style>
</head>
<body>
<h1>Top-10k Preview</h1>
<div>
  <div class="metric"><strong>Total rows</strong><div>{{n}}</div></div>
  <div class="metric"><strong>Sum USD</strong><div>${{sum_usd}}</div></div>
  <div class="metric"><strong>Median USD</strong><div>${{med_usd}}</div></div>
  <div class="metric"><strong>Mean lead score</strong><div>{{mean_ls}}</div></div>
</div>
<h3>Top 50 by USD</h3>
<table>
<tr><th>Address</th><th>USD</th><th>Lead</th><th>Exchange?</th></tr>
{% for r in top %}
<tr>
  <td><code>{{r.address}}</code></td>
  <td>${{ '%.2f'|format(r.usd_value) }}</td>
  <td>{{r.lead_score}}</td>
  <td>{{'Y' if r.exchange_deposit_flag else 'N'}}</td>
</tr>
{% endfor %}
</table>
<p style="opacity:0.7;font-size:0.9em">Autogenerated preview</p>
</body>
</html>
"""

def main(csv_path, out_dir):
    out = Path(out_dir); out.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(csv_path)
    top = df.sort_values("usd_value", ascending=False).head(50)
    html = Template(HTML).render(
        n=len(df),
        sum_usd=int(df["usd_value"].fillna(0).sum()),
        med_usd=int(df["usd_value"].fillna(0).median()),
        mean_ls=round(df["lead_score"].fillna(0).mean(), 1),
        top=top.to_dict(orient="records")
    )
    (out / "index.html").write_text(html)
    print("Wrote dashboard", out / "index.html")


if __name__ == "__main__":
    import sys
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "data/run_final/delivery/dashboard")
